name: rannabondhu
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # For Bangla localization and dates
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # For Backend API calls
  http: ^1.2.0

  # For Local Database (Fridge Tracker)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # For State Management
  provider: ^6.1.2
  
  # For saving login state
  shared_preferences: ^2.2.2
  
  # For the Pie Chart
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Hive code generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  
  # --- ADD THIS PACKAGE ---
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0
  # --- END OF ADDITION ---

flutter:
  uses-material-design: true

  # Make sure your assets folder is declared
  assets:
    - assets/icon/


# --- ADD THIS ENTIRE SECTION AT THE BOTTOM ---
# This is the configuration for the icon generator
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # (Your app's min SDK)
# --- END OF NEW SECTION ---